apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ${environment}-cluster-certificate-issuer
spec:
  acme:
    email: ${email}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: ${environment}-cluster-certificate-issuer-account-secret
    solvers:
    - http01:
        ingress:
          class: nginx