stages:
   - dependencies
   - build
   - deploy 
  

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "RXP-1000" || ($CI_MERGE_REQUEST_IID && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "develop" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "staging")
      variables:
        IMAGE_ENVIRONMENT: qa
        RXPLATFORM_ENVIRONMENT: qa
        CLUSTER_LOCATION: us-central1
        CURRENT_BRANCH: develop


variables:
  PROJECT_ID:
  COMPOSER_AUTH: $COMPOSER_AUTH
  IMAGES_PREFIX: gcr.io/$PROJECT_ID/rxplatform/mock-server
  HELPER_IMAGES_PREFIX: $IMAGES_PREFIX/helpers
  FULL_IMAGES_PREFIX: $IMAGES_PREFIX/$IMAGE_ENVIRONMENT
  TESTER_IMAGE_NAME: $HELPER_IMAGES_PREFIX/tester
  MYSQL_IMAGE_NAME: $HELPER_IMAGES_PREFIX/mysql
  MONGO_IMAGE_NAME: $HELPER_IMAGES_PREFIX/mongo
  REVIEW_ENVIRONMENT_IMAGE_NAME: $HELPER_IMAGES_PREFIX/review-environment
  #JIRA_IMAGE_NAME: $HELPER_IMAGES_PREFIX/jira
  WEB_IMAGE_NAME: $IMAGES_PREFIX/$RXPLATFORM_ENVIRONMENT/mock-server
  CLUSTER_NAME: $RXPLATFORM_ENVIRONMENT-cluster

.dependencies:
  stage: dependencies

  needs: []

  rules:
    - when: never

  image: google/cloud-sdk

  script:
    - cp $DEPENDENCY_DOCKERFILE Dockerfile
    - gcloud builds submit --config cloudbuild-generic.yaml --substitutions "_IMAGE_NAME=$DEPENDENCY_IMAGE,COMMIT_SHA=$CI_COMMIT_SHA" --gcs-log-dir=gs://rxmg-infrastructure_cloudbuild/source

  allow_failure: true

dependencies:review_environment:
  extends: .dependencies

  rules:
    - when: manual

  variables:
    DEPENDENCY_DOCKERFILE: deploy/helpers/review-environment/Dockerfile-review-environment
    DEPENDENCY_IMAGE: $REVIEW_ENVIRONMENT_IMAGE_NAME

build:web:
  stage: build
  
  needs: []

  image: google/cloud-sdk
  allow_failure: true

  script:
    - cp deploy/Dockerfile-web Dockerfile
    - gcloud builds submit --config cloudbuild.yaml --substitutions "_IMAGE_NAME=$WEB_IMAGE_NAME,COMMIT_SHA=$CI_COMMIT_SHA,_COMPOSER_AUTH=$COMPOSER_AUTH" --gcs-log-dir=gs://rxmg-infrastructure_cloudbuild/source



.deploy:
  stage: deploy

  rules:
    - when: never

  image: google/cloud-sdk

  before_script:
    - echo ".deploy Stage"
    - export USE_GKE_GCLOUD_AUTH_PLUGIN=True
    - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B53DC80D13EDEF05 AA16FCBCA621E701
    - apt-get remove -y google-cloud-cli-gke-gcloud-auth-plugin
    - apt-get clean
    - apt-get update && apt-get install -y apt-utils google-cloud-sdk-gke-gcloud-auth-plugin gettext-base
    - gcloud container clusters get-credentials "$CLUSTER_NAME" --zone "$CLUSTER_LOCATION" --project "$PROJECT_ID"

review_environment:web:
  extends: .deploy

  rules:
    - when: manual

  needs: ["build:web"]
  image: $REVIEW_ENVIRONMENT_IMAGE_NAME
  

  resource_group: $RXPLATFORM_ENVIRONMENT/web

  environment:
    name: $RXPLATFORM_ENVIRONMENT/web

  script:
    - echo "Deploying..."
  
  after_script:
     - kubectl get namespace | grep -q "^$RXPLATFORM_ENVIRONMENT " || kubectl create namespace $RXPLATFORM_ENVIRONMENT
     - export APP_NAME=mock-server
     - export REPLICA_COUNT=2
     - export IMAGE_URL=$WEB_IMAGE_NAME:$CI_COMMIT_SHA
     - export PORT=8080
     - envsubst < deployment.yaml | kubectl apply -f - --namespace=$RXPLATFORM_ENVIRONMENT