apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  qa-mock-service-service-ingress
  namespace: qa
spec:
  rules:
  - host: qa-mock-service-service.rxmg.app
    http:
      paths:
      - backend:
          service:
            name: mock-server-service
            port:
              number: 80
        pathType: ImplementationSpecific